apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zzbh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zzbh
    app.kubernetes.io/part-of: byoc-app-xkuu
  name: zzbh
spec:
  rules:
  - host: zzbh-byoc-rbxw-tenant.apps.a5902b8f1ad0509bb8ae.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: zzbh
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
