apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zzbh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zzbh
    app.kubernetes.io/part-of: byoc-app-xkuu
  name: zzbh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: zzbh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: zzbh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-rbxw-tenant/byoc-app-xkuu/zzbh@sha256:3a866e2b53e180b64103faf0d8a4bf06e29061b27b796313d4e25179a4d02be3
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
